In [10]:
import requests

API_KEY = 'a6f13e22dcc6488f8bc64b5e8ea8ceed'
DATE_FROM = '2020-02-01'
DATE_TO = '2020-10-01'
url = f"https://api-v2.deepsearch.com/v1/articles/economy?page=100&page_size=100&keyword=(아파트 OR 매매)&date_from={DATE_FROM}&date_to={DATE_TO}&api_key={API_KEY}"
try:
    # GET 요청 보내기
    response = requests.get(url)

    if response.status_code == 200:
        data = response.json()
        print("요청 성공! 데이터 : ")
        data
    else:
        print(f"요청 실패 : {response.status_code}")
        print(f"응답 내용 : {response.text}")

except requests.exceptions.RequestException as e:
    print(f"요청 중 오류 발생 : {e}")

요청 성공! 데이터 :

In [11]:
data

{'detail': {'message': 'success', 'code': 'SUCCESS', 'ok': True},
 'total_items': 91871,
 'total_pages': 100,
 'page': 100,
 'page_size': 100,
 'data': [{'id': '951583795214160109',
   'sections': ['economy'],
   'title': '法 "유령주식 11억원에 매도한 삼성증권 직원 과징금, 적법"',
   'publisher': '스포츠서울',
   'author': '권오철',
   'summary': '서울행정법원 행정5부(박양준 부장판사)는 전 삼성증권 직원 A씨가 증권선물위원회(증선위)를 상대로 낸 과징금 부과처분 취소 소송에서 원고 패소 판결했다고 30일 밝혔다.\n\n매도 주문 가능성을 확인하고 싶었다면 소액 매도 주문만 시도하거나 시장가보다 높은 가격에 주문을 시도해야 했는데 A씨는 오기 입력된 주식 전체를 시장가로 매도 주문해 삼성증권 주가를 급락시켰다”고 판시했다.\n\n당시 주식을 잘못 배당받은 A씨를 비롯한 삼성증권 직원 10여명이 해당 주식에 대한 매도 주문을 내면서 삼성증권 주가는 장중 최대 11.7% 폭락했으며 거래가 중지되기도 했다.',
   'highlight': None,
   'score': None,
   'image_url': 'https://ddi-cdn.deepsearch.com/news/economy/2020/08/30/951583795214160109/000-76873d6ebbc5307b824b9c9c119384e98d16cd8e.jpg',
   'thumbnail_url': None,
   'content_url': 'http://www.sportsseoul.com/news/read/952315',
   'esg': None,
   'companies': [{'name': '삼성증권',
     'symbol': '016360',
     'exchange': 'KRX',
     'sentiment': 'negative'}],
   'entities': [{'type': 'company', 'name': '삼성증권'}],
   'published_at': '2020-08-30T15:37:00',
   'body': None},
  {'id': '951582578979246309',
   'sections': ['economy'],
   'title': '美, 獨 중고차 시장 신차의 2배...완성차가 주도',
   'publisher': '파이낸셜뉴스',
   'author': '김병덕',
   'summary': '완성차 브랜드 \'인증 증고차\'가 성장 이끌어 국내 1.2배에 불과...불신,낙후된 시장 인식 "국내도 완성차 업체 진출해 성장 시켜야" [파이낸셜뉴스] 미국, 독일 등 선진국 중고차 시장은 신차의 2배가 넘는 규모로 급성장하고 있는 반면 국내는 아직도 음지 시장에 머물러 있다는 지적이다.\n\n미국의 경우 완성차 브랜드의 인증 중고차(CPO)를 중심으로 엄격한 성능 점검과 품질 보증이 이뤄지며 시장을 성장시켰다.\n\n이 때문에 국내에서도 완성차 브랜드의 중고차 시장 진출은 반드시 해결해야 할 과제로 꼽힌다.',
   'highlight': None,
   'score': None,
   'image_url': 'https://ddi-cdn.deepsearch.com/news/economy/2020/08/30/951582578979246309/000-4efe58370be2723cb9a9a4a818e3adb4a986eb50.jpg',
   'thumbnail_url': None,
   'content_url': 'http://www.fnnews.com/news/202008301132046396',
   'esg': None,
   'companies': [],
   'entities': [],
   'published_at': '2020-08-30T15:32:00',
   'body': None},
  {'id': '951581971891491208',
   'sections': ['economy'],
   'title': '[성호건의 전지적 토지관점]토지 매입 전 알아두면 마음 편한 상식3',
   'publisher': '스포츠서울',
   'author': '',
   'summary': '◇ 토목공사의 개념을 알아야 한다 소비자들은 토지를 볼 때 ‘바로 집을 지을 수 있는 토지’를 원한다.\n\n따라서 토지를 찾을 때 건축을 할 예정이라면 토목공사가 어디까지 돼있는지 구체적으로 확인하도록 하자.\n\n따라서 팔 때를 고려하지 못한 토지와 전원주택은 애물단지가 될 확률이 높다.',
   'highlight': None,
   'score': None,
   'image_url': 'https://ddi-cdn.deepsearch.com/news/economy/2020/08/30/951581971891491208/000-e4382289daadb4955fa56876fbd95d5667b9157f.jpg',
   'thumbnail_url': None,
   'content_url': 'http://www.sportsseoul.com/news/read/952305',
   'esg': None,
   'companies': [],
   'entities': [],
   'published_at': '2020-08-30T15:30:00',
   'body': None},
  {'id': '951580754943545420',
   'sections': ['economy'],
   'title': '美·獨 중고차 시장, 신차의 2배…"완성차업체 품질관리 영향"',
   'publisher': '데일리안',
   'author': '조인영',
   'summary': '독일도 중고차 시장 규모가 720만대로 신차(360만대)의 2배에 달했다.\n\n독일도 신차 대비 중고차 판매 대수가 2배 이상으로 유지됐다.\n\n인증 중고차·정확한 정보로 소비자 신뢰 높여 미국과 유럽, 일본 등 해외 주요국은 완성차 브랜드가 신차와 중고차를 모두 판매하기 때문에 품질 수준이 높은 중고차를 공급하고 있다.',
   'highlight': None,
   'score': None,
   'image_url': 'https://ddi-cdn.deepsearch.com/news/economy/2020/08/30/951580754943545420/000-7796aaab7192562e695cf2553b3d712033b5a255.jpeg',
   'thumbnail_url': None,
   'content_url': 'https://www.dailian.co.kr/news/view/915837/',
   'esg': None,
   'companies': [{'name': 'SK',
     'symbol': '034730',
     'exchange': 'KRX',
     'sentiment': 'positive'}],
   'entities': [{'type': 'company', 'name': 'SK'}],
   'published_at': '2020-08-30T15:24:00',
   'body': None},
  {'id': '951580754943545422',
   'sections': ['economy'],
   'title': '분양가상한제 시행 앞두고 서울 분양물량 작년 6배 늘어나',
   'publisher': '연합뉴스',
   'author': '강민지',
   'summary': '강민지 기자 = 정부가 민간택지 분양가 상한제 시행을 앞둔 지난달 전국 공동주택 분양 물량은 5만8천866채로 작년 동월 대비 158.1% 증가, 서울 분양 물량은 1만5천589채로 작년 대비 499.3% 증가했다고 30일 발표했다.\n\n사진은 이날 서울 63빌딩에서 본 서울 아파트 모습.',
   'highlight': None,
   'score': None,
   'image_url': 'https://ddi-cdn.deepsearch.com/news/economy/2020/08/30/951580754943545422/000-04fd897469fa4fb2531eb507a6b7cc576e9f644d.jpg',
   'thumbnail_url': None,
   'content_url': 'http://yna.kr/PYH20200830067100013?did=1196m',
   'esg': None,
   'companies': [],
   'entities': [],
   'published_at': '2020-08-30T15:23:00',
   'body': None},
  {'id': '951580754943545414',
   'sections': ['economy'],
   'title': '분양가상한제 시행 앞두고 서울 분양물량 작년의 6배 급증',
   'publisher': '연합뉴스',
   'author': '강민지',
   'summary': '강민지 기자 = 정부가 민간택지 분양가 상한제 시행을 앞둔 지난달 전국 공동주택 분양 물량은 5만8천866채로 작년 동월 대비 158.1% 증가, 서울 분양 물량은 1만5천589채로 작년 대비 499.3% 늘었다고 30일 발표했다.\n\n사진은 이날 서울 63빌딩에서 본 서울 아파트 모습.',
   'highlight': None,
   'score': None,
   'image_url': 'https://ddi-cdn.deepsearch.com/news/economy/2020/08/30/951580754943545414/000-11774b9d6c06e9bbb3525e67af9b7eae25ff52da.jpg',
   'thumbnail_url': None,
   'content_url': 'http://yna.kr/PYH20200830066600013?did=1196m',
   'esg': None,
   'companies': [],
   'entities': [],
   'published_at': '2020-08-30T15:23:00',
   'body': None},
  {'id': '951580754943545413',
   'sections': ['economy'],
   'title': '분양가상한제 시행 앞두고 서울 분양물량 작년의 6배 증가',
   'publisher': '연합뉴스',
   'author': '강민지',
   'summary': '강민지 기자 = 정부가 민간택지 분양가 상한제 시행을 앞둔 지난달 전국 공동주택 분양 물량은 5만8천866채로 작년 동월 대비 158.1% 증가, 서울 분양 물량은 1만5천589채로 작년 대비 499.3% 증가했다고 30일 발표했다.\n\n사진은 이날 서울 63빌딩에서 본 서울 아파트 모습.',
   'highlight': None,
   'score': None,
   'image_url': 'https://ddi-cdn.deepsearch.com/news/economy/2020/08/30/951580754943545413/000-07f5ea2d65a31f11d64e7477ca84a61299459c15.jpg',
   'thumbnail_url': None,
   'content_url': 'http://yna.kr/PYH20200830066700013?did=1196m',
   'esg': None,
   'companies': [],
   'entities': [],
   'published_at': '2020-08-30T15:23:00',
   'body': None},
  {'id': '951580754943545412',
   'sections': ['economy'],
   'title': '분양가상한제 시행 앞두고 서울 분양물량 작년의 6배 ↑',
   'publisher': '연합뉴스',
   'author': '강민지',
   'summary': '강민지 기자 = 정부가 민간택지 분양가 상한제 시행을 앞둔 지난달 전국 공동주택 분양 물량은 5만8천866채로 작년 동월 대비 158.1% 증가, 서울 분양 물량은 1만5천589채로 작년 대비 499.3% 증가했다고 30일 발표했다.\n\n사진은 이날 서울 63빌딩에서 본 서울 아파트 모습.',
   'highlight': None,
   'score': None,
   'image_url': 'https://ddi-cdn.deepsearch.com/news/economy/2020/08/30/951580754943545412/000-fd34fee741cbebe74a14916a2a07af37bba1231b.jpg',
   'thumbnail_url': None,
   'content_url': 'http://yna.kr/PYH20200830066800013?did=1196m',
   'esg': None,
   'companies': [],
   'entities': [],
   'published_at': '2020-08-30T15:23:00',
   'body': None},
  {'id': '951580754943545411',
   'sections': ['economy'],
   'title': '분양가상한제 시행 앞두고 서울 분양물량 전년대비 6배 급증',
   'publisher': '연합뉴스',
   'author': '강민지',
   'summary': '강민지 기자 = 정부가 민간택지 분양가 상한제 시행을 앞둔 지난달 전국 공동주택 분양 물량은 5만8천866채로 작년 동월 대비 158.1% 증가, 서울 분양 물량은 1만5천589채로 작년 대비 499.3% 증가했다고 30일 발표했다.\n\n사진은 이날 서울 63빌딩에서 본 서울 아파트 모습.',
   'highlight': None,
   'score': None,
   'image_url': 'https://ddi-cdn.deepsearch.com/news/economy/2020/08/30/951580754943545411/000-373149daf3fa9ed08093cf84693870d5d9e7e77f.jpg',
   'thumbnail_url': None,
   'content_url': 'http://yna.kr/PYH20200830066900013?did=1196m',
   'esg': None,
   'companies': [],
   'entities': [],
   'published_at': '2020-08-30T15:23:00',
   'body': None},
  {'id': '951580754943545410',
   'sections': ['economy'],
   'title': '분양가상한제 시행 앞두고 서울 분양물량 작년의 6배',
   'publisher': '연합뉴스',
   'author': '강민지',
   'summary': '강민지 기자 = 정부가 민간택지 분양가 상한제 시행을 앞둔 지난달 전국 공동주택 분양 물량은 5만8천866채로 작년 동월 대비 158.1% 증가, 서울 분양 물량은 1만5천589채로 작년 대비 499.3% 증가했다고 30일 발표했다.\n\n사진은 이날 서울 63빌딩에서 본 서울 아파트 모습.',
   'highlight': None,
   'score': None,
   'image_url': 'https://ddi-cdn.deepsearch.com/news/economy/2020/08/30/951580754943545410/000-52036857c736037f386531a0148016bcc7edaf0f.jpg',
   'thumbnail_url': None,
   'content_url': 'http://yna.kr/PYH20200830067000013?did=1196m',
   'esg': None,
   'companies': [],
   'entities': [],
   'published_at': '2020-08-30T15:23:00',
   'body': None},
  {'id': '951580151165096145',
   'sections': ['economy'],
   'title': "'주택공급 선행지표' 인허가 작년 대비 46% 증가",
   'publisher': '파이낸셜뉴스',
   'author': '김현우',
   'summary': '7월 유형별 주택 인허가는 아파트가 3만611가구를 기록, 전년 대비 59.2% 증가했다.\n\n주택 착공실적도 전년 대비 증가세를 기록 중이다.\n\n7월 주택 준공실적은 전년 동월(4만446가구) 대비 42.6% 늘어난 5만7663가구로 집계됐다.',
   'highlight': None,
   'score': None,
   'image_url': 'https://ddi-cdn.deepsearch.com/news/economy/2020/08/30/951580151165096145/000-01548d245ae922e2fc2610e976a704954918bc13.jpg',
   'thumbnail_url': None,
   'content_url': 'http://www.fnnews.com/news/202008301421136160',
   'esg': None,
   'companies': [],
   'entities': [],
   'published_at': '2020-08-30T15:23:00',
   'body': None},
  {'id': '951580151165096146',
   'sections': ['economy'],
   'title': '장관이 "일부 몇몇"이라던 10억 아파트…\'노도강\'에서도 속출',
   'publisher': '한국경제',
   'author': '장현주',
   'summary': '서울에서 상대적으로 집값이 낮은 ‘노도강(노원·도봉·강북구)’이 잇따라 ‘10억원 클럽’(전용 84㎡ 기준)에 가입하고 있다.\n\n지난 6월 10억원에 거래된 미아동 송천센트레빌 전용 84㎡에 이어 강북구에서 두 번째로 10억 클럽 가입을 눈앞에 두고 있다.\n\n노원구에서는 중계동 청구3차와 건영3차 전용 84㎡가 지난 6월 이미 10억원대를 돌파했다.',
   'highlight': None,
   'score': None,
   'image_url': 'https://ddi-cdn.deepsearch.com/news/economy/2020/08/30/951580151165096146/000-b4b1ac1f86b79862d50eb6281afc011949af2604.jpg',
   'thumbnail_url': None,
   'content_url': 'https://www.hankyung.com/realestate/article/202008302295i',
   'esg': None,
   'companies': [],
   'entities': [],
   'published_at': '2020-08-30T15:22:00',
   'body': None},
  {'id': '951579547705413730',
   'sections': ['economy'],
   'title': '서울 아파트 한채, 가족 월급 한 푼 안쓰고 11년 넘게 모아야',
   'publisher': '경향신문',
   'author': '박광연',
   'summary': '30일 KB국민은행에 따르면 올해 2분기 기준 서울의 KB아파트 PIR 지수는 11.4로, 2년 전(9.9)보다 1.5 높아졌다.\n\n2년 전과 비교해 서울 가구소득은 4624만원에서 5443만원으로 11.7%(820만원) 올랐지만, 주택가격은 4억5584만원에서 6억2000만원으로 36.0%(1억6417만원) 상승한 탓에 PIR이 더 높아진 것이다.\n\n이같은 부담은 올해 2분기 경기도의 아파트 PIR(8.0)이나 인천(7.5)에 비해서도 높다고 국민은행은 집계했다.',
   'highlight': None,
   'score': None,
   'image_url': None,
   'thumbnail_url': None,
   'content_url': 'http://news.khan.co.kr/kh_news/khan_art_view.html?artid=202008301520001&code=920501',
   'esg': None,
   'companies': [],
   'entities': [],
   'published_at': '2020-08-30T15:20:00',
   'body': None},
  {'id': '951577773158306190',
   'sections': ['economy'],
   'title': "충남도, 불법 부동산거래 뿌리뽑는다···'떴다방' 등",
   'publisher': '뉴시스',
   'author': '유효상',
   'summary': '30일 도에 따르면 성성2지구는 최근 고분양가, 청약과열로 부동산 투기가 우려되는 지역으로 분류된다.\n\n실제로 성성2지구는 아파트 분양 청약률이 119대 1을 상회하는 등 부동산 시장이 과열된 상태다.\n\n특히 천막 등 임시 중개시설물(떴다방) 설치, 중개보조원을 동원한 불법 부동산 중개행위를 중점 단속한다.',
   'highlight': None,
   'score': None,
   'image_url': 'https://ddi-cdn.deepsearch.com/news/economy/2020/08/30/951577773158306190/000-73513a212a13c57122b3e0211ffcefffc49e8cf7.jpg',
   'thumbnail_url': None,
   'content_url': 'http://www.newsis.com/view/?id=NISX20200830_0001147667&cID=10807&pID=10800',
   'esg': None,
   'companies': [],
   'entities': [],
   'published_at': '2020-08-30T15:10:00',
   'body': None},
  {'id': '951576591429931400',
   'sections': ['economy'],
   'title': '현대리바트, 부산 인테리어 시장 공략 박차',
   'publisher': '아이뉴스24',
   'author': '이연춘',
   'summary': '부산시 수영구에 초대형 \'리바트 부산 전시장\' 오픈 현대리바트가 부산광역시 수영구에 초대형 가정용 가구 전시장을 선보인다.\n\n현대백화점그룹 계열의 토탈 인테리어기업 현대리바트는 부산광역시 수영구 망미동에 ‘리바트 부산 전시장(이하 부산 전시장)’을 오픈한다고 30일 밝혔다.\n\n현대리바트 관계자는 "부산 전시장이 들어서는 수영구와 인근의 해운대구는 핵심 고객층인 30~50대 비중이 부산지역에서 가장 높고 초고층 아파트 등 고급 주거공간과 상업시설이 점차 확대되는 등 배후 수요가 풍부하다"고 설명했다.',
   'highlight': None,
   'score': None,
   'image_url': 'https://ddi-cdn.deepsearch.com/news/economy/2020/08/30/951576591429931400/000-29caec7922cf810023596b6acefe1569539262bb.jpg',
   'thumbnail_url': None,
   'content_url': 'http://www.inews24.com/view/1294720',
   'esg': None,
   'companies': [{'name': '현대리바트',
     'symbol': '079430',
     'exchange': 'KRX',
     'sentiment': 'positive'}],
   'entities': [{'type': 'company', 'name': '디자인'},
    {'type': 'company', 'name': '현대리바트'}],
   'published_at': '2020-08-30T15:09:00',
   'body': None},
  {'id': '951574228996592129',
   'sections': ['economy'],
   'title': "'金포' 다시 '김포'로…부동산 규제지역 피한다",
   'publisher': '이데일리',
   'author': '정두리',
   'summary': '최근 1달간 매매 거래 1000건 넘어…신고가도 속출 풍무동 대장주 센트럴 푸르지오 84㎡ 7억원대 앞둬 전문가 “김포 상승폭 갈수록 낮아지는 점 주목해야” 추가 규제지역 1순위서 비규제지역 유지 가능성 커져[이데일리 정두리 기자] 수도권 대부분을 조정대상지역으로 묶은 6·17대책에서 파주와 함께 규제에서 제외된 경기 김포시가 정부의 레이더망에서 벗어날 것으로 보인다.\n\n(사진=정두리 기자)한국감정원의 월간아파트 가격동향에 따르면 6·17 대책 발표 직후인 김포의 6월4주차 상승률은 1.88%로 전국 최고를 기록했지만 이후 매주 0.9~0.58% 사이로 상승폭이 크지 않다.\n\n여경희 부동산114 수석연구원은 “김포는 7월 말까지 큰 폭의 가격 상승을 보였으나 8월 초부터 서서히 가격 상승폭이 줄고 있다”면서 ...',
   'highlight': None,
   'score': None,
   'image_url': 'https://ddi-cdn.deepsearch.com/news/economy/2020/08/30/951574228996592129/000-008e6d7b4763c14fb94089963ea0383cd64daff5.jpg',
   'thumbnail_url': None,
   'content_url': 'http://www.edaily.co.kr/news/newspath.asp?newsid=01922086625872568',
   'esg': None,
   'companies': [],
   'entities': [],
   'published_at': '2020-08-30T14:58:00',
   'body': None},
  {'id': '951574228996592123',
   'sections': ['economy'],
   'title': '서울서 아파트 사려면 가족월급 11.4년치 모아야',
   'publisher': '한국일보',
   'author': '유환구',
   'summary': 'PIR은 주택 가격을 가구 소득으로 나눈 값으로, 가구 전체가 소득을 한 푼도 쓰지 않고 모았을 경우 주택을 구입하는 데 걸리는 기간을 뜻한다.\n\n따라서 PIR 지수 11.4는 가구 수입을 전혀 소비하지 않고 모았을 때 11.4년이 걸린다는 뜻이다.\n\nPIR 지수가 계속 높아진 것은 가구 소득 상승치보다 주택 가격 상승폭이 더 컸기 때문이다.',
   'highlight': None,
   'score': None,
   'image_url': 'https://ddi-cdn.deepsearch.com/news/economy/2020/08/30/951574228996592123/000-48f7e2b353c19712a04d5db1398dfd65afa24f8e.jpg',
   'thumbnail_url': None,
   'content_url': 'https://hankookilbo.com/News/Read/A2020083014510003243?did=NA',
   'esg': None,
   'companies': [],
   'entities': [],
   'published_at': '2020-08-30T14:58:00',
   'body': None},
  {'id': '951572459507814777',
   'sections': ['economy'],
   'title': '춘천 복권판매점 2곳 로또 2등 당첨',
   'publisher': '뉴시스',
   'author': '김경목',
   'summary': "춘천 복권명당 '대박의터·모닝글로리' 김경목 기자 = 강원 춘천의 복권판매점 2곳에서 로또복권 2등 당첨의 행운이 터졌다.\n\n대박의터에서는 올 들어 916회 1등, 920회 2등 행운이 이어지는 등 도내 신 복권명당이 되고 있다.\n\n모닝글로리 온의점도 지난 922회 추첨에서 2등 복권이 당첨된 것을 비롯 최근 수년간 당첨 행운이 찾아온 복권명당이다.",
   'highlight': None,
   'score': None,
   'image_url': 'https://ddi-cdn.deepsearch.com/news/economy/2020/08/30/951572459507814777/000-433f8a7e467cd7d908eeac3e905cc6e0e49cd3af.jpg',
   'thumbnail_url': None,
   'content_url': 'http://www.newsis.com/view/?id=NISX20200830_0001147640&cID=10805&pID=10800',
   'esg': None,
   'companies': [{'name': '강원',
     'symbol': '114190',
     'exchange': 'KRX',
     'sentiment': 'neutral'}],
   'entities': [{'type': 'company', 'name': '강원'}],
   'published_at': '2020-08-30T14:51:00',
   'body': None},
  {'id': '951571870598172930',
   'sections': ['economy'],
   'title': '8·15 도심집회발 확산 본격화…대구 교회 3곳서 44명 확진',
   'publisher': '뉴스1',
   'author': '김태환',
   'summary': '이 중 8.15 서울 도심 집회 관련 확진자는 총 369명으로 조사 중 62명이 추가됐다.\n\n특히 대구에서만 44명의 집회 관련 확진자가 밝혀졌다.\n\n서울 성북구 사랑제일교회 관련 확진자는 총 1035명으로 접촉자 조사 중 17명에게서 감염 사실이 새로 드러났다.',
   'highlight': None,
   'score': None,
   'image_url': 'https://ddi-cdn.deepsearch.com/news/economy/2020/08/30/951571870598172930/000-6c4c9d752c6241fa94852395eaa1d0e15f6e9e41.jpg',
   'thumbnail_url': None,
   'content_url': 'https://www.news1.kr/articles/?4042127',
   'esg': None,
   'companies': [],
   'entities': [],
   'published_at': '2020-08-30T14:47:00',
   'body': None},
  {'id': '951568339430412771',
   'sections': ['economy'],
   'title': "증발된 '옵티머스 5151억', 얼마나 회수할 수 있나",
   'publisher': '머니투데이',
   'author': '김소연',
   'summary': '옵티머스 사태로 묶인 투자자들의 자금만 5151억원이다.\n\n30일 금융당국 등에 따르면 현재 삼일회계법인이 옵티머스 펀드 회계실사를 진행 중이다.\n\n투자자가 돌려받을 수 있는 자금의 원천이 펀드 자산이다.',
   'highlight': None,
   'score': None,
   'image_url': 'https://ddi-cdn.deepsearch.com/news/economy/2020/08/30/951568339430412771/000-390de0706bf0db218211265d2946b1468d573dcc.jpg',
   'thumbnail_url': None,
   'content_url': 'http://news.mt.co.kr/mtview.php?no=2020082916375786011',
   'esg': None,
   'companies': [{'name': 'NH투자증권',
     'symbol': '005940',
     'exchange': 'KRX',
     'sentiment': 'negative'}],
   'entities': [{'type': 'company', 'name': 'NH투자증권'}],
   'published_at': '2020-08-30T14:34:00',
   'body': None},
  {'id': '951567175808848149',
   'sections': ['economy'],
   'title': '[속보]구로구 아파트 관련 1명 추가 확진…누적 35명',
   'publisher': '머니투데이',
   'author': '이민하',
   'summary': '30일 중앙재난안전대책본부(중대본) 정례브리핑',
   'highlight': None,
   'score': None,
   'image_url': None,
   'thumbnail_url': None,
   'content_url': 'http://news.mt.co.kr/mtview.php?no=2020083014280135034',
   'esg': None,
   'companies': [],
   'entities': [],
   'published_at': '2020-08-30T14:30:00',
   'body': None},
  {'id': '951574824273187195',
   'sections': ['economy'],
   'title': "서울 아파트 매입하는 외지인 급증…6·17대책 '빨대효과'",
   'publisher': 'MBN',
   'author': '',
   'summary': '서울에 거주하지 않는 외지인의 서울 아파트 매입이 지난달 급증한 것으로 나타났습니다.\n\n구별로 보면 지난달에는 용산구를 제외한 24개 구에서 외지인의 서울 아파트 매입이 전달(6월)보다 증가했습니다.\n\n실제로 경기와 인천의 외지인 아파트 매입은 지난달에 감소했습니다.',
   'highlight': None,
   'score': None,
   'image_url': 'https://ddi-cdn.deepsearch.com/news/economy/2020/08/30/951574824273187195/000-4b3ce2ada4f4f3e2f0955bc9e984d96839520fd9.jpg',
   'thumbnail_url': None,
   'content_url': 'http://mbn.mk.co.kr/pages/news/newsView.php?category=mbn00003&news_seq_no=4263894',
   'esg': None,
   'companies': [],
   'entities': [],
   'published_at': '2020-08-30T14:29:00',
   'body': None},
  {'id': '951565418840068541',
   'sections': ['economy'],
   'title': "[주간전망] 잇따른 호재에 코스피 더 뛴다…코로나19 확산이 '변수'",
   'publisher': '한국경제',
   'author': '한경닷컴',
   'summary': '공매도 금지 조치 연장·평균물가목표제 도입 등 상승 요인 사회적 거리두기 3단계 격상 시 충격 불가피 이번 주(31일~9월 4일) 국내 증시는 금융위원회의 공매도 금지 조치 연장, 미국 중앙은행(Fed)의 평균물가목표제 도입 등으로 상승에 무게가 실리고 있다.\n\n다만 신종 코로나바이러스 감염증(코로나19) 재확산에 따른 사회적 거리두기 3단계 격상 여부가 부담으로 작용할 전망이다.\n\n공매도 금지 조치 연장, Fed의 평균물가목표제 도입, 미국 추가 경기부양책 기대, 코로나19 백신 개발 업체들의 임상실험과 관련된 긍정적 뉴스 등 호재성 요인이 잇따르고 있어서다.',
   'highlight': None,
   'score': None,
   'image_url': 'https://ddi-cdn.deepsearch.com/news/economy/2020/08/30/951565418840068541/000-fe30df0cb037d22f3912c44f14ade40917a25786.jpg',
   'thumbnail_url': None,
   'content_url': 'https://www.hankyung.com/finance/article/2020082881926',
   'esg': None,
   'companies': [],
   'entities': [{'type': 'company', 'name': 'NH투자증권'},
    {'type': 'company', 'name': 'SK증권'}],
   'published_at': '2020-08-30T14:23:00',
   'body': None},
  {'id': '951563098781782360',
   'sections': ['economy'],
   'title': '[표]주간 유가증권·코스닥 투자주체별 매매동향(8월 24일~28일)',
   'publisher': '서울경제',
   'author': '',
   'summary': '',
   'highlight': None,
   'score': None,
   'image_url': 'https://ddi-cdn.deepsearch.com/news/economy/2020/08/30/951563098781782360/000-cdcd1375133820ae90df9a67f97cbbcfadaef533.jpg',
   'thumbnail_url': None,
   'content_url': 'https://www.sedaily.com/NewsView/1Z6S469G5C',
   'esg': None,
   'companies': [],
   'entities': [],
   'published_at': '2020-08-30T14:15:00',
   'body': None},
  {'id': '951563098781782357',
   'sections': ['economy'],
   'title': '[속보]구로구아파트-금천구 축산업체 관련 2명 추가…총 35명 확진',
   'publisher': 'SBS CNBC',
   'author': '김정연',
   'summary': '구로구아파트-금천구 축산업체 관련 2명 추가…총 35명 확진',
   'highlight': None,
   'score': None,
   'image_url': None,
   'thumbnail_url': None,
   'content_url': 'https://cnbc.sbs.co.kr/article_hub/10000994600',
   'esg': None,
   'companies': [],
   'entities': [],
   'published_at': '2020-08-30T14:15:00',
   'body': None},
  {'id': '951562514196467973',
   'sections': ['economy'],
   'title': '서울에 아파트 사려면 가족 전체가 11.4년 굶어야',
   'publisher': '한국경제',
   'author': '',
   'summary': 'PIR은 주택 가격을 가구 소득으로 나눈 값이다.\n\nPIR 11.4는 한 가족이 생활비를 전혀 쓰지 않고 11.4년을 모아야 아파트 한 채 살 돈을 모은다는 뜻이다.\n\n서울의 PIR 수치는 지난 2016년 1분기 9.0을 기록한 이후 가구 소득 상승치보다 주택 가격 상승폭이 커지며 5분기 연속 상승세를 보였다.',
   'highlight': None,
   'score': None,
   'image_url': 'https://ddi-cdn.deepsearch.com/news/economy/2020/08/30/951562514196467973/000-ad388a0928cc151b70d171dafc39c9a1f3595290.jpg',
   'thumbnail_url': None,
   'content_url': 'https://www.hankyung.com/realestate/article/2020083020667',
   'esg': None,
   'companies': [],
   'entities': [],

In [3]:
data.keys()

dict_keys(['detail', 'total_items', 'total_pages', 'page', 'page_size', 'data'])

In [4]:
len(data['data'])

100

In [5]:
data['data']

[{'id': '951583795214160109',
  'sections': ['economy'],
  'title': '法 "유령주식 11억원에 매도한 삼성증권 직원 과징금, 적법"',
  'publisher': '스포츠서울',
  'author': '권오철',
  'summary': '서울행정법원 행정5부(박양준 부장판사)는 전 삼성증권 직원 A씨가 증권선물위원회(증선위)를 상대로 낸 과징금 부과처분 취소 소송에서 원고 패소 판결했다고 30일 밝혔다.\n\n매도 주문 가능성을 확인하고 싶었다면 소액 매도 주문만 시도하거나 시장가보다 높은 가격에 주문을 시도해야 했는데 A씨는 오기 입력된 주식 전체를 시장가로 매도 주문해 삼성증권 주가를 급락시켰다”고 판시했다.\n\n당시 주식을 잘못 배당받은 A씨를 비롯한 삼성증권 직원 10여명이 해당 주식에 대한 매도 주문을 내면서 삼성증권 주가는 장중 최대 11.7% 폭락했으며 거래가 중지되기도 했다.',
  'highlight': None,
  'score': None,
  'image_url': 'https://ddi-cdn.deepsearch.com/news/economy/2020/08/30/951583795214160109/000-76873d6ebbc5307b824b9c9c119384e98d16cd8e.jpg',
  'thumbnail_url': None,
  'content_url': 'http://www.sportsseoul.com/news/read/952315',
  'esg': None,
  'companies': [{'name': '삼성증권',
    'symbol': '016360',
    'exchange': 'KRX',
    'sentiment': 'negative'}],
  'entities': [{'type': 'company', 'name': '삼성증권'}],
  'published_at': '2020-08-30T15:37:00',
  'body': None},
 {'id': '951582578979246309',
  'sections': ['economy'],
  'title': '美, 獨 중고차 시장 신차의 2배...완성차가 주도',
  'publisher': '파이낸셜뉴스',
  'author': '김병덕',
  'summary': '완성차 브랜드 \'인증 증고차\'가 성장 이끌어 국내 1.2배에 불과...불신,낙후된 시장 인식 "국내도 완성차 업체 진출해 성장 시켜야" [파이낸셜뉴스] 미국, 독일 등 선진국 중고차 시장은 신차의 2배가 넘는 규모로 급성장하고 있는 반면 국내는 아직도 음지 시장에 머물러 있다는 지적이다.\n\n미국의 경우 완성차 브랜드의 인증 중고차(CPO)를 중심으로 엄격한 성능 점검과 품질 보증이 이뤄지며 시장을 성장시켰다.\n\n이 때문에 국내에서도 완성차 브랜드의 중고차 시장 진출은 반드시 해결해야 할 과제로 꼽힌다.',
  'highlight': None,
  'score': None,
  'image_url': 'https://ddi-cdn.deepsearch.com/news/economy/2020/08/30/951582578979246309/000-4efe58370be2723cb9a9a4a818e3adb4a986eb50.jpg',
  'thumbnail_url': None,
  'content_url': 'http://www.fnnews.com/news/202008301132046396',
  'esg': None,
  'companies': [],
  'entities': [],
  'published_at': '2020-08-30T15:32:00',
  'body': None},
 {'id': '951581971891491208',
  'sections': ['economy'],
  'title': '[성호건의 전지적 토지관점]토지 매입 전 알아두면 마음 편한 상식3',
  'publisher': '스포츠서울',
  'author': '',
  'summary': '◇ 토목공사의 개념을 알아야 한다 소비자들은 토지를 볼 때 ‘바로 집을 지을 수 있는 토지’를 원한다.\n\n따라서 토지를 찾을 때 건축을 할 예정이라면 토목공사가 어디까지 돼있는지 구체적으로 확인하도록 하자.\n\n따라서 팔 때를 고려하지 못한 토지와 전원주택은 애물단지가 될 확률이 높다.',
  'highlight': None,
  'score': None,
  'image_url': 'https://ddi-cdn.deepsearch.com/news/economy/2020/08/30/951581971891491208/000-e4382289daadb4955fa56876fbd95d5667b9157f.jpg',
  'thumbnail_url': None,
  'content_url': 'http://www.sportsseoul.com/news/read/952305',
  'esg': None,
  'companies': [],
  'entities': [],
  'published_at': '2020-08-30T15:30:00',
  'body': None},
 {'id': '951580754943545420',
  'sections': ['economy'],
  'title': '美·獨 중고차 시장, 신차의 2배…"완성차업체 품질관리 영향"',
  'publisher': '데일리안',
  'author': '조인영',
  'summary': '독일도 중고차 시장 규모가 720만대로 신차(360만대)의 2배에 달했다.\n\n독일도 신차 대비 중고차 판매 대수가 2배 이상으로 유지됐다.\n\n인증 중고차·정확한 정보로 소비자 신뢰 높여 미국과 유럽, 일본 등 해외 주요국은 완성차 브랜드가 신차와 중고차를 모두 판매하기 때문에 품질 수준이 높은 중고차를 공급하고 있다.',
  'highlight': None,
  'score': None,
  'image_url': 'https://ddi-cdn.deepsearch.com/news/economy/2020/08/30/951580754943545420/000-7796aaab7192562e695cf2553b3d712033b5a255.jpeg',
  'thumbnail_url': None,
  'content_url': 'https://www.dailian.co.kr/news/view/915837/',
  'esg': None,
  'companies': [{'name': 'SK',
    'symbol': '034730',
    'exchange': 'KRX',
    'sentiment': 'positive'}],
  'entities': [{'type': 'company', 'name': 'SK'}],
  'published_at': '2020-08-30T15:24:00',
  'body': None},
 {'id': '951580754943545422',
  'sections': ['economy'],
  'title': '분양가상한제 시행 앞두고 서울 분양물량 작년 6배 늘어나',
  'publisher': '연합뉴스',
  'author': '강민지',
  'summary': '강민지 기자 = 정부가 민간택지 분양가 상한제 시행을 앞둔 지난달 전국 공동주택 분양 물량은 5만8천866채로 작년 동월 대비 158.1% 증가, 서울 분양 물량은 1만5천589채로 작년 대비 499.3% 증가했다고 30일 발표했다.\n\n사진은 이날 서울 63빌딩에서 본 서울 아파트 모습.',
  'highlight': None,
  'score': None,
  'image_url': 'https://ddi-cdn.deepsearch.com/news/economy/2020/08/30/951580754943545422/000-04fd897469fa4fb2531eb507a6b7cc576e9f644d.jpg',
  'thumbnail_url': None,
  'content_url': 'http://yna.kr/PYH20200830067100013?did=1196m',
  'esg': None,
  'companies': [],
  'entities': [],
  'published_at': '2020-08-30T15:23:00',
  'body': None},
 {'id': '951580754943545414',
  'sections': ['economy'],
  'title': '분양가상한제 시행 앞두고 서울 분양물량 작년의 6배 급증',
  'publisher': '연합뉴스',
  'author': '강민지',
  'summary': '강민지 기자 = 정부가 민간택지 분양가 상한제 시행을 앞둔 지난달 전국 공동주택 분양 물량은 5만8천866채로 작년 동월 대비 158.1% 증가, 서울 분양 물량은 1만5천589채로 작년 대비 499.3% 늘었다고 30일 발표했다.\n\n사진은 이날 서울 63빌딩에서 본 서울 아파트 모습.',
  'highlight': None,
  'score': None,
  'image_url': 'https://ddi-cdn.deepsearch.com/news/economy/2020/08/30/951580754943545414/000-11774b9d6c06e9bbb3525e67af9b7eae25ff52da.jpg',
  'thumbnail_url': None,
  'content_url': 'http://yna.kr/PYH20200830066600013?did=1196m',
  'esg': None,
  'companies': [],
  'entities': [],
  'published_at': '2020-08-30T15:23:00',
  'body': None},
 {'id': '951580754943545413',
  'sections': ['economy'],
  'title': '분양가상한제 시행 앞두고 서울 분양물량 작년의 6배 증가',
  'publisher': '연합뉴스',
  'author': '강민지',
  'summary': '강민지 기자 = 정부가 민간택지 분양가 상한제 시행을 앞둔 지난달 전국 공동주택 분양 물량은 5만8천866채로 작년 동월 대비 158.1% 증가, 서울 분양 물량은 1만5천589채로 작년 대비 499.3% 증가했다고 30일 발표했다.\n\n사진은 이날 서울 63빌딩에서 본 서울 아파트 모습.',
  'highlight': None,
  'score': None,
  'image_url': 'https://ddi-cdn.deepsearch.com/news/economy/2020/08/30/951580754943545413/000-07f5ea2d65a31f11d64e7477ca84a61299459c15.jpg',
  'thumbnail_url': None,
  'content_url': 'http://yna.kr/PYH20200830066700013?did=1196m',
  'esg': None,
  'companies': [],
  'entities': [],
  'published_at': '2020-08-30T15:23:00',
  'body': None},
 {'id': '951580754943545412',
  'sections': ['economy'],
  'title': '분양가상한제 시행 앞두고 서울 분양물량 작년의 6배 ↑',
  'publisher': '연합뉴스',
  'author': '강민지',
  'summary': '강민지 기자 = 정부가 민간택지 분양가 상한제 시행을 앞둔 지난달 전국 공동주택 분양 물량은 5만8천866채로 작년 동월 대비 158.1% 증가, 서울 분양 물량은 1만5천589채로 작년 대비 499.3% 증가했다고 30일 발표했다.\n\n사진은 이날 서울 63빌딩에서 본 서울 아파트 모습.',
  'highlight': None,
  'score': None,
  'image_url': 'https://ddi-cdn.deepsearch.com/news/economy/2020/08/30/951580754943545412/000-fd34fee741cbebe74a14916a2a07af37bba1231b.jpg',
  'thumbnail_url': None,
  'content_url': 'http://yna.kr/PYH20200830066800013?did=1196m',
  'esg': None,
  'companies': [],
  'entities': [],
  'published_at': '2020-08-30T15:23:00',
  'body': None},
 {'id': '951580754943545411',
  'sections': ['economy'],
  'title': '분양가상한제 시행 앞두고 서울 분양물량 전년대비 6배 급증',
  'publisher': '연합뉴스',
  'author': '강민지',
  'summary': '강민지 기자 = 정부가 민간택지 분양가 상한제 시행을 앞둔 지난달 전국 공동주택 분양 물량은 5만8천866채로 작년 동월 대비 158.1% 증가, 서울 분양 물량은 1만5천589채로 작년 대비 499.3% 증가했다고 30일 발표했다.\n\n사진은 이날 서울 63빌딩에서 본 서울 아파트 모습.',
  'highlight': None,
  'score': None,
  'image_url': 'https://ddi-cdn.deepsearch.com/news/economy/2020/08/30/951580754943545411/000-373149daf3fa9ed08093cf84693870d5d9e7e77f.jpg',
  'thumbnail_url': None,
  'content_url': 'http://yna.kr/PYH20200830066900013?did=1196m',
  'esg': None,
  'companies': [],
  'entities': [],
  'published_at': '2020-08-30T15:23:00',
  'body': None},
 {'id': '951580754943545410',
  'sections': ['economy'],
  'title': '분양가상한제 시행 앞두고 서울 분양물량 작년의 6배',
  'publisher': '연합뉴스',
  'author': '강민지',
  'summary': '강민지 기자 = 정부가 민간택지 분양가 상한제 시행을 앞둔 지난달 전국 공동주택 분양 물량은 5만8천866채로 작년 동월 대비 158.1% 증가, 서울 분양 물량은 1만5천589채로 작년 대비 499.3% 증가했다고 30일 발표했다.\n\n사진은 이날 서울 63빌딩에서 본 서울 아파트 모습.',
  'highlight': None,
  'score': None,
  'image_url': 'https://ddi-cdn.deepsearch.com/news/economy/2020/08/30/951580754943545410/000-52036857c736037f386531a0148016bcc7edaf0f.jpg',
  'thumbnail_url': None,
  'content_url': 'http://yna.kr/PYH20200830067000013?did=1196m',
  'esg': None,
  'companies': [],
  'entities': [],
  'published_at': '2020-08-30T15:23:00',
  'body': None},
 {'id': '951580151165096145',
  'sections': ['economy'],
  'title': "'주택공급 선행지표' 인허가 작년 대비 46% 증가",
  'publisher': '파이낸셜뉴스',
  'author': '김현우',
  'summary': '7월 유형별 주택 인허가는 아파트가 3만611가구를 기록, 전년 대비 59.2% 증가했다.\n\n주택 착공실적도 전년 대비 증가세를 기록 중이다.\n\n7월 주택 준공실적은 전년 동월(4만446가구) 대비 42.6% 늘어난 5만7663가구로 집계됐다.',
  'highlight': None,
  'score': None,
  'image_url': 'https://ddi-cdn.deepsearch.com/news/economy/2020/08/30/951580151165096145/000-01548d245ae922e2fc2610e976a704954918bc13.jpg',
  'thumbnail_url': None,
  'content_url': 'http://www.fnnews.com/news/202008301421136160',
  'esg': None,
  'companies': [],
  'entities': [],
  'published_at': '2020-08-30T15:23:00',
  'body': None},
 {'id': '951580151165096146',
  'sections': ['economy'],
  'title': '장관이 "일부 몇몇"이라던 10억 아파트…\'노도강\'에서도 속출',
  'publisher': '한국경제',
  'author': '장현주',
  'summary': '서울에서 상대적으로 집값이 낮은 ‘노도강(노원·도봉·강북구)’이 잇따라 ‘10억원 클럽’(전용 84㎡ 기준)에 가입하고 있다.\n\n지난 6월 10억원에 거래된 미아동 송천센트레빌 전용 84㎡에 이어 강북구에서 두 번째로 10억 클럽 가입을 눈앞에 두고 있다.\n\n노원구에서는 중계동 청구3차와 건영3차 전용 84㎡가 지난 6월 이미 10억원대를 돌파했다.',
  'highlight': None,
  'score': None,
  'image_url': 'https://ddi-cdn.deepsearch.com/news/economy/2020/08/30/951580151165096146/000-b4b1ac1f86b79862d50eb6281afc011949af2604.jpg',
  'thumbnail_url': None,
  'content_url': 'https://www.hankyung.com/realestate/article/202008302295i',
  'esg': None,
  'companies': [],
  'entities': [],
  'published_at': '2020-08-30T15:22:00',
  'body': None},
 {'id': '951579547705413730',
  'sections': ['economy'],
  'title': '서울 아파트 한채, 가족 월급 한 푼 안쓰고 11년 넘게 모아야',
  'publisher': '경향신문',
  'author': '박광연',
  'summary': '30일 KB국민은행에 따르면 올해 2분기 기준 서울의 KB아파트 PIR 지수는 11.4로, 2년 전(9.9)보다 1.5 높아졌다.\n\n2년 전과 비교해 서울 가구소득은 4624만원에서 5443만원으로 11.7%(820만원) 올랐지만, 주택가격은 4억5584만원에서 6억2000만원으로 36.0%(1억6417만원) 상승한 탓에 PIR이 더 높아진 것이다.\n\n이같은 부담은 올해 2분기 경기도의 아파트 PIR(8.0)이나 인천(7.5)에 비해서도 높다고 국민은행은 집계했다.',
  'highlight': None,
  'score': None,
  'image_url': None,
  'thumbnail_url': None,
  'content_url': 'http://news.khan.co.kr/kh_news/khan_art_view.html?artid=202008301520001&code=920501',
  'esg': None,
  'companies': [],
  'entities': [],
  'published_at': '2020-08-30T15:20:00',
  'body': None},
 {'id': '951577773158306190',
  'sections': ['economy'],
  'title': "충남도, 불법 부동산거래 뿌리뽑는다···'떴다방' 등",
  'publisher': '뉴시스',
  'author': '유효상',
  'summary': '30일 도에 따르면 성성2지구는 최근 고분양가, 청약과열로 부동산 투기가 우려되는 지역으로 분류된다.\n\n실제로 성성2지구는 아파트 분양 청약률이 119대 1을 상회하는 등 부동산 시장이 과열된 상태다.\n\n특히 천막 등 임시 중개시설물(떴다방) 설치, 중개보조원을 동원한 불법 부동산 중개행위를 중점 단속한다.',
  'highlight': None,
  'score': None,
  'image_url': 'https://ddi-cdn.deepsearch.com/news/economy/2020/08/30/951577773158306190/000-73513a212a13c57122b3e0211ffcefffc49e8cf7.jpg',
  'thumbnail_url': None,
  'content_url': 'http://www.newsis.com/view/?id=NISX20200830_0001147667&cID=10807&pID=10800',
  'esg': None,
  'companies': [],
  'entities': [],
  'published_at': '2020-08-30T15:10:00',
  'body': None},
 {'id': '951576591429931400',
  'sections': ['economy'],
  'title': '현대리바트, 부산 인테리어 시장 공략 박차',
  'publisher': '아이뉴스24',
  'author': '이연춘',
  'summary': '부산시 수영구에 초대형 \'리바트 부산 전시장\' 오픈 현대리바트가 부산광역시 수영구에 초대형 가정용 가구 전시장을 선보인다.\n\n현대백화점그룹 계열의 토탈 인테리어기업 현대리바트는 부산광역시 수영구 망미동에 ‘리바트 부산 전시장(이하 부산 전시장)’을 오픈한다고 30일 밝혔다.\n\n현대리바트 관계자는 "부산 전시장이 들어서는 수영구와 인근의 해운대구는 핵심 고객층인 30~50대 비중이 부산지역에서 가장 높고 초고층 아파트 등 고급 주거공간과 상업시설이 점차 확대되는 등 배후 수요가 풍부하다"고 설명했다.',
  'highlight': None,
  'score': None,
  'image_url': 'https://ddi-cdn.deepsearch.com/news/economy/2020/08/30/951576591429931400/000-29caec7922cf810023596b6acefe1569539262bb.jpg',
  'thumbnail_url': None,
  'content_url': 'http://www.inews24.com/view/1294720',
  'esg': None,
  'companies': [{'name': '현대리바트',
    'symbol': '079430',
    'exchange': 'KRX',
    'sentiment': 'positive'}],
  'entities': [{'type': 'company', 'name': '디자인'},
   {'type': 'company', 'name': '현대리바트'}],
  'published_at': '2020-08-30T15:09:00',
  'body': None},
 {'id': '951574228996592129',
  'sections': ['economy'],
  'title': "'金포' 다시 '김포'로…부동산 규제지역 피한다",
  'publisher': '이데일리',
  'author': '정두리',
  'summary': '최근 1달간 매매 거래 1000건 넘어…신고가도 속출 풍무동 대장주 센트럴 푸르지오 84㎡ 7억원대 앞둬 전문가 “김포 상승폭 갈수록 낮아지는 점 주목해야” 추가 규제지역 1순위서 비규제지역 유지 가능성 커져[이데일리 정두리 기자] 수도권 대부분을 조정대상지역으로 묶은 6·17대책에서 파주와 함께 규제에서 제외된 경기 김포시가 정부의 레이더망에서 벗어날 것으로 보인다.\n\n(사진=정두리 기자)한국감정원의 월간아파트 가격동향에 따르면 6·17 대책 발표 직후인 김포의 6월4주차 상승률은 1.88%로 전국 최고를 기록했지만 이후 매주 0.9~0.58% 사이로 상승폭이 크지 않다.\n\n여경희 부동산114 수석연구원은 “김포는 7월 말까지 큰 폭의 가격 상승을 보였으나 8월 초부터 서서히 가격 상승폭이 줄고 있다”면서 ...',
  'highlight': None,
  'score': None,
  'image_url': 'https://ddi-cdn.deepsearch.com/news/economy/2020/08/30/951574228996592129/000-008e6d7b4763c14fb94089963ea0383cd64daff5.jpg',
  'thumbnail_url': None,
  'content_url': 'http://www.edaily.co.kr/news/newspath.asp?newsid=01922086625872568',
  'esg': None,
  'companies': [],
  'entities': [],
  'published_at': '2020-08-30T14:58:00',
  'body': None},
 {'id': '951574228996592123',
  'sections': ['economy'],
  'title': '서울서 아파트 사려면 가족월급 11.4년치 모아야',
  'publisher': '한국일보',
  'author': '유환구',
  'summary': 'PIR은 주택 가격을 가구 소득으로 나눈 값으로, 가구 전체가 소득을 한 푼도 쓰지 않고 모았을 경우 주택을 구입하는 데 걸리는 기간을 뜻한다.\n\n따라서 PIR 지수 11.4는 가구 수입을 전혀 소비하지 않고 모았을 때 11.4년이 걸린다는 뜻이다.\n\nPIR 지수가 계속 높아진 것은 가구 소득 상승치보다 주택 가격 상승폭이 더 컸기 때문이다.',
  'highlight': None,
  'score': None,
  'image_url': 'https://ddi-cdn.deepsearch.com/news/economy/2020/08/30/951574228996592123/000-48f7e2b353c19712a04d5db1398dfd65afa24f8e.jpg',
  'thumbnail_url': None,
  'content_url': 'https://hankookilbo.com/News/Read/A2020083014510003243?did=NA',
  'esg': None,
  'companies': [],
  'entities': [],
  'published_at': '2020-08-30T14:58:00',
  'body': None},
 {'id': '951572459507814777',
  'sections': ['economy'],
  'title': '춘천 복권판매점 2곳 로또 2등 당첨',
  'publisher': '뉴시스',
  'author': '김경목',
  'summary': "춘천 복권명당 '대박의터·모닝글로리' 김경목 기자 = 강원 춘천의 복권판매점 2곳에서 로또복권 2등 당첨의 행운이 터졌다.\n\n대박의터에서는 올 들어 916회 1등, 920회 2등 행운이 이어지는 등 도내 신 복권명당이 되고 있다.\n\n모닝글로리 온의점도 지난 922회 추첨에서 2등 복권이 당첨된 것을 비롯 최근 수년간 당첨 행운이 찾아온 복권명당이다.",
  'highlight': None,
  'score': None,
  'image_url': 'https://ddi-cdn.deepsearch.com/news/economy/2020/08/30/951572459507814777/000-433f8a7e467cd7d908eeac3e905cc6e0e49cd3af.jpg',
  'thumbnail_url': None,
  'content_url': 'http://www.newsis.com/view/?id=NISX20200830_0001147640&cID=10805&pID=10800',
  'esg': None,
  'companies': [{'name': '강원',
    'symbol': '114190',
    'exchange': 'KRX',
    'sentiment': 'neutral'}],
  'entities': [{'type': 'company', 'name': '강원'}],
  'published_at': '2020-08-30T14:51:00',
  'body': None},
 {'id': '951571870598172930',
  'sections': ['economy'],
  'title': '8·15 도심집회발 확산 본격화…대구 교회 3곳서 44명 확진',
  'publisher': '뉴스1',
  'author': '김태환',
  'summary': '이 중 8.15 서울 도심 집회 관련 확진자는 총 369명으로 조사 중 62명이 추가됐다.\n\n특히 대구에서만 44명의 집회 관련 확진자가 밝혀졌다.\n\n서울 성북구 사랑제일교회 관련 확진자는 총 1035명으로 접촉자 조사 중 17명에게서 감염 사실이 새로 드러났다.',
  'highlight': None,
  'score': None,
  'image_url': 'https://ddi-cdn.deepsearch.com/news/economy/2020/08/30/951571870598172930/000-6c4c9d752c6241fa94852395eaa1d0e15f6e9e41.jpg',
  'thumbnail_url': None,
  'content_url': 'https://www.news1.kr/articles/?4042127',
  'esg': None,
  'companies': [],
  'entities': [],
  'published_at': '2020-08-30T14:47:00',
  'body': None},
 {'id': '951568339430412771',
  'sections': ['economy'],
  'title': "증발된 '옵티머스 5151억', 얼마나 회수할 수 있나",
  'publisher': '머니투데이',
  'author': '김소연',
  'summary': '옵티머스 사태로 묶인 투자자들의 자금만 5151억원이다.\n\n30일 금융당국 등에 따르면 현재 삼일회계법인이 옵티머스 펀드 회계실사를 진행 중이다.\n\n투자자가 돌려받을 수 있는 자금의 원천이 펀드 자산이다.',
  'highlight': None,
  'score': None,
  'image_url': 'https://ddi-cdn.deepsearch.com/news/economy/2020/08/30/951568339430412771/000-390de0706bf0db218211265d2946b1468d573dcc.jpg',
  'thumbnail_url': None,
  'content_url': 'http://news.mt.co.kr/mtview.php?no=2020082916375786011',
  'esg': None,
  'companies': [{'name': 'NH투자증권',
    'symbol': '005940',
    'exchange': 'KRX',
    'sentiment': 'negative'}],
  'entities': [{'type': 'company', 'name': 'NH투자증권'}],
  'published_at': '2020-08-30T14:34:00',
  'body': None},
 {'id': '951567175808848149',
  'sections': ['economy'],
  'title': '[속보]구로구 아파트 관련 1명 추가 확진…누적 35명',
  'publisher': '머니투데이',
  'author': '이민하',
  'summary': '30일 중앙재난안전대책본부(중대본) 정례브리핑',
  'highlight': None,
  'score': None,
  'image_url': None,
  'thumbnail_url': None,
  'content_url': 'http://news.mt.co.kr/mtview.php?no=2020083014280135034',
  'esg': None,
  'companies': [],
  'entities': [],
  'published_at': '2020-08-30T14:30:00',
  'body': None},
 {'id': '951574824273187195',
  'sections': ['economy'],
  'title': "서울 아파트 매입하는 외지인 급증…6·17대책 '빨대효과'",
  'publisher': 'MBN',
  'author': '',
  'summary': '서울에 거주하지 않는 외지인의 서울 아파트 매입이 지난달 급증한 것으로 나타났습니다.\n\n구별로 보면 지난달에는 용산구를 제외한 24개 구에서 외지인의 서울 아파트 매입이 전달(6월)보다 증가했습니다.\n\n실제로 경기와 인천의 외지인 아파트 매입은 지난달에 감소했습니다.',
  'highlight': None,
  'score': None,
  'image_url': 'https://ddi-cdn.deepsearch.com/news/economy/2020/08/30/951574824273187195/000-4b3ce2ada4f4f3e2f0955bc9e984d96839520fd9.jpg',
  'thumbnail_url': None,
  'content_url': 'http://mbn.mk.co.kr/pages/news/newsView.php?category=mbn00003&news_seq_no=4263894',
  'esg': None,
  'companies': [],
  'entities': [],
  'published_at': '2020-08-30T14:29:00',
  'body': None},
 {'id': '951565418840068541',
  'sections': ['economy'],
  'title': "[주간전망] 잇따른 호재에 코스피 더 뛴다…코로나19 확산이 '변수'",
  'publisher': '한국경제',
  'author': '한경닷컴',
  'summary': '공매도 금지 조치 연장·평균물가목표제 도입 등 상승 요인 사회적 거리두기 3단계 격상 시 충격 불가피 이번 주(31일~9월 4일) 국내 증시는 금융위원회의 공매도 금지 조치 연장, 미국 중앙은행(Fed)의 평균물가목표제 도입 등으로 상승에 무게가 실리고 있다.\n\n다만 신종 코로나바이러스 감염증(코로나19) 재확산에 따른 사회적 거리두기 3단계 격상 여부가 부담으로 작용할 전망이다.\n\n공매도 금지 조치 연장, Fed의 평균물가목표제 도입, 미국 추가 경기부양책 기대, 코로나19 백신 개발 업체들의 임상실험과 관련된 긍정적 뉴스 등 호재성 요인이 잇따르고 있어서다.',
  'highlight': None,
  'score': None,
  'image_url': 'https://ddi-cdn.deepsearch.com/news/economy/2020/08/30/951565418840068541/000-fe30df0cb037d22f3912c44f14ade40917a25786.jpg',
  'thumbnail_url': None,
  'content_url': 'https://www.hankyung.com/finance/article/2020082881926',
  'esg': None,
  'companies': [],
  'entities': [{'type': 'company', 'name': 'NH투자증권'},
   {'type': 'company', 'name': 'SK증권'}],
  'published_at': '2020-08-30T14:23:00',
  'body': None},
 {'id': '951563098781782360',
  'sections': ['economy'],
  'title': '[표]주간 유가증권·코스닥 투자주체별 매매동향(8월 24일~28일)',
  'publisher': '서울경제',
  'author': '',
  'summary': '',
  'highlight': None,
  'score': None,
  'image_url': 'https://ddi-cdn.deepsearch.com/news/economy/2020/08/30/951563098781782360/000-cdcd1375133820ae90df9a67f97cbbcfadaef533.jpg',
  'thumbnail_url': None,
  'content_url': 'https://www.sedaily.com/NewsView/1Z6S469G5C',
  'esg': None,
  'companies': [],
  'entities': [],
  'published_at': '2020-08-30T14:15:00',
  'body': None},
 {'id': '951563098781782357',
  'sections': ['economy'],
  'title': '[속보]구로구아파트-금천구 축산업체 관련 2명 추가…총 35명 확진',
  'publisher': 'SBS CNBC',
  'author': '김정연',
  'summary': '구로구아파트-금천구 축산업체 관련 2명 추가…총 35명 확진',
  'highlight': None,
  'score': None,
  'image_url': None,
  'thumbnail_url': None,
  'content_url': 'https://cnbc.sbs.co.kr/article_hub/10000994600',
  'esg': None,
  'companies': [],
  'entities': [],
  'published_at': '2020-08-30T14:15:00',
  'body': None},
 {'id': '951562514196467973',
  'sections': ['economy'],
  'title': '서울에 아파트 사려면 가족 전체가 11.4년 굶어야',
  'publisher': '한국경제',
  'author': '',
  'summary': 'PIR은 주택 가격을 가구 소득으로 나눈 값이다.\n\nPIR 11.4는 한 가족이 생활비를 전혀 쓰지 않고 11.4년을 모아야 아파트 한 채 살 돈을 모은다는 뜻이다.\n\n서울의 PIR 수치는 지난 2016년 1분기 9.0을 기록한 이후 가구 소득 상승치보다 주택 가격 상승폭이 커지며 5분기 연속 상승세를 보였다.',
  'highlight': None,
  'score': None,
  'image_url': 'https://ddi-cdn.deepsearch.com/news/economy/2020/08/30/951562514196467973/000-ad388a0928cc151b70d171dafc39c9a1f3595290.jpg',
  'thumbnail_url': None,
  'content_url': 'https://www.hankyung.com/realestate/article/2020083020667',
  'esg': None,
  'companies': [],
  'entities': [],
  'published_at': '2020-08-30T14:12:00',
  'body': None},
 {'id': '951561357780717738',
  'sections': ['economy'],
  'title': '전국이 ‘똘똘한 한채’ 狂風?…7월 외지인 서울 아파트 매입, 올해 최고치',
  'publisher': '조선비즈',
  'author': '유병훈',
  'summary': '서울에 거주하지 않는 외지인의 서울 아파트 매입이 지난달 급증한 것으로 나타났다.\n\n구별로 보면 지난달에는 용산구를 제외한 24개 구에서 외지인의 서울 아파트 매입이 지난 6월보다 증가했다.\n\n경기도와 인천의 외지인 아파트 매입은 지난달에 비해 오히려 감소했다.',
  'highlight': None,
  'score': None,
  'image_url': 'https://ddi-cdn.deepsearch.com/news/economy/2020/08/30/951561357780717738/000-ed7baf51d8cc703b5834689ba52e6e43d6f5eae0.jpg',
  'thumbnail_url': None,

In [9]:
data['data'][0]['published_at']

'2020-08-30T15:37:00'

In [2]:
import requests
from datetime import datetime
from dateutil.relativedelta import relativedelta
from tqdm import tqdm
API_KEY = 'a6f13e22dcc6488f8bc64b5e8ea8ceed'
date = datetime(2018, 7, 1)
articles = []

for i in tqdm(range(1815)):
    start_date = date + relativedelta(weeks=i)
    end_date = start_date + relativedelta(weeks=1)

    url = f"https://api-v2.deepsearch.com/v1/articles/economy?page=1&page_size=100&keyword=(아파트 OR 매매)&date_from={start_date.strftime('%Y-%m-%d')}&date_to={end_date.strftime('%Y-%m-%d')}&api_key={API_KEY}"

    try:
        response = requests.get(url)
        if response.status_code == 200:
            data = response.json()
            #print(f"{start_date.strftime('%Y-%m-%d')} 데이터 요청 성공, 기사 개수: {len(data['data'])}")

            for item in data['data']:
                article = {
                    "기사 ID": item['id'],
                    "기사 제목": item['title'],
                    "출판사": item['publisher'],
                    "게시 일자": item['published_at'],
                    "URL": item['content_url'],
                    "본문": item['summary']
                }
                articles.append(article)
        else:
            print(f"요청 실패 : {response.status_code}")
            print(f"응답 내용 : {response.text}")

    except requests.exceptions.RequestException as e:
        print(f"요청 중 오류 발생 : {e}")

100%|█████████████████████████████████████████████████| 1815/1815 [43:12<00:00,  1.43s/it]

In [3]:
len(articles)

37437

In [4]:
import pandas as pd

In [5]:
df = pd.DataFrame(articles)

In [6]:
df.head()

,기사 ID,기사 제목,출판사,게시 일자,URL,본문
0,667568117265862965,대전 아파트 지하주차장서 불…승용차 1대 불에 타,연합뉴스,2018-07-08T21:56:00,http://app.yonhapnews.co.kr/YNA/Basic/SNS/r.as...,유의주 기자 = 8일 오후 6시 52분께 대전시 지족동의 한 아파트단지 지하 2층 ...
1,667554978877018304,"""빈집 천지"" 울산 주택시장 앞이 캄캄",파이낸셜뉴스,2018-07-08T21:05:00,http://www.fnnews.com/news/201807082103231161,특히 지난해부터 본격 하락세에 접어든 울산 동구의 집값이 지난달 현대중공업이 해양사...
2,667525756506739145,"[항만 재개발 사업 본격화] '민자 1호' 고현항 재개발 1단계 완료, 투자 '탄력'",부산일보,2018-07-08T19:09:00,http://news20.busan.com/controller/newsControl...,거제 고현항 항만재개발 사업 조감도.\n\n거제 고현항 재개발 사업은 낙후된 항구 ...
3,667525756506739144,[추천매물] 토지(매매)外,부산일보,2018-07-08T19:09:00,http://news20.busan.com/controller/newsControl...,"■토지(매매)=부산 강서구 범방동 1029㎡(311평), 준주거지역, 대로변, 매매..."
4,667525756506739142,[Hot 팁] 113. 보유세 강화 후 시장 전망,부산일보,2018-07-08T19:09:00,http://news20.busan.com/controller/newsControl...,이번 조치로 다주택자와 1주택자는 보유세 부담 때문에 추가적인 주택 투자를 망설이게...

In [7]:
df['출판사'].nunique()

228

In [8]:
df.drop('기사 ID',axis=1, inplace=True)

In [27]:
df.columns = ['title','content','url','date','publisher']

In [29]:
df = df[['title','date','content','publisher','url']]

In [30]:
df.head()

,title,date,content,publisher,url
0,대전 아파트 지하주차장서 불…승용차 1대 불에 타,2018-07-08T21:56:00,유의주 기자 = 8일 오후 6시 52분께 대전시 지족동의 한 아파트단지 지하 2층 ...,연합뉴스,http://app.yonhapnews.co.kr/YNA/Basic/SNS/r.as...
1,"""빈집 천지"" 울산 주택시장 앞이 캄캄",2018-07-08T21:05:00,특히 지난해부터 본격 하락세에 접어든 울산 동구의 집값이 지난달 현대중공업이 해양사...,파이낸셜뉴스,http://www.fnnews.com/news/201807082103231161
2,"[항만 재개발 사업 본격화] '민자 1호' 고현항 재개발 1단계 완료, 투자 '탄력'",2018-07-08T19:09:00,거제 고현항 항만재개발 사업 조감도.\n\n거제 고현항 재개발 사업은 낙후된 항구 ...,부산일보,http://news20.busan.com/controller/newsControl...
3,[추천매물] 토지(매매)外,2018-07-08T19:09:00,"■토지(매매)=부산 강서구 범방동 1029㎡(311평), 준주거지역, 대로변, 매매...",부산일보,http://news20.busan.com/controller/newsControl...
4,[Hot 팁] 113. 보유세 강화 후 시장 전망,2018-07-08T19:09:00,이번 조치로 다주택자와 1주택자는 보유세 부담 때문에 추가적인 주택 투자를 망설이게...,부산일보,http://news20.busan.com/controller/newsControl...

In [31]:
df['date'] = pd.to_datetime(df['date']).dt.date

In [32]:
df['content'] = df['content'].astype(str)

In [33]:
df.head()

,title,date,content,publisher,url
0,대전 아파트 지하주차장서 불…승용차 1대 불에 타,2018-07-08,유의주 기자 = 8일 오후 6시 52분께 대전시 지족동의 한 아파트단지 지하 2층 ...,연합뉴스,http://app.yonhapnews.co.kr/YNA/Basic/SNS/r.as...
1,"""빈집 천지"" 울산 주택시장 앞이 캄캄",2018-07-08,특히 지난해부터 본격 하락세에 접어든 울산 동구의 집값이 지난달 현대중공업이 해양사...,파이낸셜뉴스,http://www.fnnews.com/news/201807082103231161
2,"[항만 재개발 사업 본격화] '민자 1호' 고현항 재개발 1단계 완료, 투자 '탄력'",2018-07-08,거제 고현항 항만재개발 사업 조감도.\n\n거제 고현항 재개발 사업은 낙후된 항구 ...,부산일보,http://news20.busan.com/controller/newsControl...
3,[추천매물] 토지(매매)外,2018-07-08,"■토지(매매)=부산 강서구 범방동 1029㎡(311평), 준주거지역, 대로변, 매매...",부산일보,http://news20.busan.com/controller/newsControl...
4,[Hot 팁] 113. 보유세 강화 후 시장 전망,2018-07-08,이번 조치로 다주택자와 1주택자는 보유세 부담 때문에 추가적인 주택 투자를 망설이게...,부산일보,http://news20.busan.com/controller/newsControl...

In [34]:
df.to_csv("../data/interim/news/deep_search_news.csv", index=False)

In [36]:
df.isna().sum()

title        0
date         0
content      0
publisher    0
url          0
dtype: int64